/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {
      colors: {
        "primary-light": "var(--text-primary-light)",
        "primary-dark": "var(--text-primary-dark)",
        "primary-main": "var(--text-primary-main)",
        "primary": "var(--text-primary)",
        "warning-light": "var(--text-warning-light)",
        "warning-dark": "var(--text-warning-dark)",
        "warning-main": "var(--text-warning-main)",
        "warning": "var(--text-warning)",
        "main-light": "var(--text-main-light)",
        "main-dark": "var(--text-main-dark)",
        "main-main": "var(--text-main-main)",
        "main": "var(--text-main)",
        "secondary-light": "var(--text-secondary-light)",
        "secondary-dark": "var(--text-secondary-dark)",
        "secondary-main": "var(--text-secondary-main)",
        "secondary": "var(--text-secondary)",
        "error-light": "var(--text-error-light)",
        "error-dark": "var(--text-error-dark)",
        "error-main": "var(--text-error-main)",
        "error": "var(--text-error)",
        "success-light": "var(--text-success-light)",
        "success-dark": "var(--text-success-dark)",
        "success-main": "var(--text-success-main)",
        "success": "var(--text-success)",
        "info-light": "var(--text-info-light)",
        "info-dark": "var(--text-info-dark)",
        "info-main": "var(--text-info-main)",
        "info": "var(--text-info)"
      },
      backgroundColor: {
        "surface-light": "var(--bg-surface-light)",
        "surface-dark": "var(--bg-surface-dark)",
        "surface-main": "var(--bg-surface-main)",
        "surface": "var(--bg-surface)",
        "primary-light": "var(--bg-primary-light)",
        "primary-dark": "var(--bg-primary-dark)",
        "primary-main": "var(--bg-primary-main)",
        "primary": "var(--bg-primary)",
        "main-dark": "var(--bg-main-dark)",
        "main-light": "var(--bg-main-light)",
        "main-main": "var(--bg-main-main)",
        "main": "var(--bg-main)",
        "secondary-light": "var(--bg-secondary-light)",
        "secondary-dark": "var(--bg-secondary-dark)",
        "secondary-main": "var(--bg-secondary-main)",
        "secondary": "var(--bg-secondary)",
        "success-light": "var(--bg-success-light)",
        "success-dark": "var(--bg-success-dark)",
        "success-main": "var(--bg-success-main)",
        "success": "var(--bg-success)",
        "error-light": "var(--bg-error-light)",
        "error-dark": "var(--bg-error-dark)",
        "error-main": "var(--bg-error-main)",
        "error": "var(--bg-error)",
        "warning-light": "var(--bg-warning-light)",
        "warning-dark": "var(--bg-warning-dark)",
        "warning-main": "var(--bg-warning-main)",
        "warning": "var(--bg-warning)"
      },
    },
  },
  plugins: [],
}

